# Generated by Django 3.0.7 on 2020-06-23 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City_Name', models.CharField(default='', max_length=30, verbose_name='City_Name')),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField(default=0, verbose_name='Year')),
                ('temperature', models.IntegerField(default=0, verbose_name='temperature')),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.City')),
            ],
        ),
    ]
